### ISSUE TITLE
Possible Copyright & Licence violation

### ISSUE THREAD

**Issue by assanges** [GO-LiFE/map8#1]
Greetings!

Your Map8 Platform has been identified as posing potential copyright and licence issues since the platform has adapted @OpenStreetMap and @mapbox data without any credits or copyright notice (as below), unfortunately.

![Landing page](https://i.imgur.com/jSTEjhi.png)
![gomp.js incl. geojson-vt & mapbox-gl](https://i.imgur.com/nQXooWN.png)

e.g. a typical credit for a browsable electronic map for using OSM
![Example](https://www.openstreetmap.org/assets/attribution_example-94d158290ba9cdb2d10f479c27deacbee11593aeaaae19f244e53676df89cf7f.png)

The OpenStreetMap (OSM) cartography is licenced as CC BY-SA, which may only redistribute under the same licence if. As an OSM community member (@OSMHackTW), I would like to sincerely urge you to comply with the guideline and legal codes, you can find more details on the [OSM copyright page](https://www.openstreetmap.org/copyright) and [mapbox ToS page](https://www.mapbox.com/tos/).

Sincerely.
2019-05-12

您好！貴司之台灣圖霸地圖平台使用了 OpenStreetMap （OSM/開放街圖）圖資以及 Mapbox 部分代碼，然而遺憾地該平台並未列明所使用資料來源或出處（如下圖所示）。

![Landing page](https://i.imgur.com/jSTEjhi.png)
![gomp.js incl. geojson-vt & mapbox-gl](https://i.imgur.com/nQXooWN.png)

e.g. 使用OSM圖資的電子地圖典型範例
![Example](https://www.openstreetmap.org/assets/attribution_example-94d158290ba9cdb2d10f479c27deacbee11593aeaaae19f244e53676df89cf7f.png)

開放街圖圖資係採用「創用 CC BY-SA」授權，該授權要求使用時必須給予適當表彰，以及於重混、轉換素材時，必須依原授權條款發布。身為開放街圖社群的一員，請容敝人敦促貴司遵守相關指引和授權條款，貴司可至[OSM 著作權頁面](https://www.openstreetmap.org/copyright)和[mapbox 使用條款頁面](https://www.mapbox.com/tos/)獲取更多資訊。順頌

時祺
2019-05-12

**Comment by golife-sysop** [comment]
Hi @assanges and @openstreetmap and @mapbox 各位女士先生您們好, 

非常感謝您的指導，並給予我們充分的時間改善。我們已經將不妥當的部分移除，今後我們也會更加謹慎。

還請您繼續給我們指導與鞭策，讓台灣的地圖產業更加進步。

由衷感謝您。
